# This file is autogenerated, do not edit by hand!
{fetchgit}: {
  registryUrl = "https://github.com/JuliaRegistries/General.git";
  registryRev = "7f2713520de85101b1a15537658a4e4cad3bb994";
  registrySha256 = "128410d495lzs60xb9ss6aq3cf1685yqcxvf0xbzpk0855x3lb3s";
  rootPackages = ["ForwardDiff" "Pluto"];
  closure = [{
  name = "Artifacts";
  uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33";
  path = "A/Artifacts";
  replaceUrlInManifest = null;
  treehash = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Artifacts.jl.git"; rev = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744"; sha256 = "0i0s26ypiwg6zyb3aqn9kiyiblkkab1mfac9plmq2jv4hggm4jfc"; };
} {
  name = "Base64";
  uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "ChainRulesCore";
  uuid = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4";
  path = "C/ChainRulesCore";
  replaceUrlInManifest = null;
  treehash = "be770c08881f7bb928dfd86d1ba83798f76cf62a";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/ChainRulesCore.jl.git"; rev = "be770c08881f7bb928dfd86d1ba83798f76cf62a"; sha256 = "0khkxdz76phjz8ifxfnyw90pfkicyvxin7mj17h35g4ibp3csij4"; };
} {
  name = "CommonSubexpressions";
  uuid = "bbf7d656-a473-5ed7-a52c-81e309532950";
  path = "C/CommonSubexpressions";
  replaceUrlInManifest = null;
  treehash = "7b8a93dba8af7e3b42fecabf646260105ac373f7";
  artifacts = {};
  src = fetchgit { url = "https://github.com/rdeits/CommonSubexpressions.jl.git"; rev = "7b8a93dba8af7e3b42fecabf646260105ac373f7"; sha256 = "0mgy90kk8ksv3l720kkk04gnhn4aqhh2dj4sp3x8yy3limngfjay"; };
} {
  name = "Compat";
  uuid = "34da2185-b29b-5c13-b0c7-acf172513d20";
  path = "C/Compat";
  replaceUrlInManifest = null;
  treehash = "dc7dedc2c2aa9faf59a55c622760a25cbefbe941";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/Compat.jl.git"; rev = "dc7dedc2c2aa9faf59a55c622760a25cbefbe941"; sha256 = "07ij7m4ca399i2bx63kghfhw15wg5pzzrazpaxic1wlpzrpssxfn"; };
} {
  name = "CompilerSupportLibraries_jll";
  uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae";
  path = "C/CompilerSupportLibraries_jll";
  replaceUrlInManifest = null;
  treehash = "8e695f735fca77e9708e795eda62afdb869cbb70";
  artifacts = {
    "424e8fcc25b26b5599a8d0f73dd5e8cac598fca8" = [{
      name = "CompilerSupportLibraries";
      url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.3+0/CompilerSupportLibraries.v0.3.3.x86_64-linux-gnu-libgfortran5.tar.gz";
      sha256 = "23771ec6d2fa014db480b5cfe8e1b6f34b2d29e8bbea8cdce1edd5f1e15cb6e0";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl.git"; rev = "8e695f735fca77e9708e795eda62afdb869cbb70"; sha256 = "0iqm61cjxilqcapz9z9w42qq799dmzfd92px2gysjdmny3v0qf4r"; };
} {
  name = "Configurations";
  uuid = "5218b696-f38b-4ac9-8b61-a12ec717816d";
  path = "C/Configurations";
  replaceUrlInManifest = null;
  treehash = "b8486a417456d2fbbe2af13e24cef459c9f42429";
  artifacts = {};
  src = fetchgit { url = "https://github.com/Roger-luo/Configurations.jl.git"; rev = "b8486a417456d2fbbe2af13e24cef459c9f42429"; sha256 = "1dz1h64nqgcv6ai70pfv2dv4mqx9rqmh08196k7j73bqlc6r00w1"; };
} {
  name = "Crayons";
  uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f";
  path = "C/Crayons";
  replaceUrlInManifest = null;
  treehash = "3f71217b538d7aaee0b69ab47d9b7724ca8afa0d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/KristofferC/Crayons.jl.git"; rev = "3f71217b538d7aaee0b69ab47d9b7724ca8afa0d"; sha256 = "0v3zhjlnb2914bxcj4myl8pgb7m31p77aj2k1bckmqs96jdph10z"; };
} {
  name = "DataAPI";
  uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a";
  path = "D/DataAPI";
  replaceUrlInManifest = null;
  treehash = "ee400abb2298bd13bfc3df1c412ed228061a2385";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/DataAPI.jl.git"; rev = "ee400abb2298bd13bfc3df1c412ed228061a2385"; sha256 = "0swk31p83fycz5cdj4fg6b0wfqj473lnx94q2fl7ybxkkc6afba7"; };
} {
  name = "DataValueInterfaces";
  uuid = "e2d170a0-9d28-54be-80f0-106bbe20a464";
  path = "D/DataValueInterfaces";
  replaceUrlInManifest = null;
  treehash = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6";
  artifacts = {};
  src = fetchgit { url = "https://github.com/queryverse/DataValueInterfaces.jl.git"; rev = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"; sha256 = "0g2wj6q7jj956nx6g7dk8x7w1c4l2xcmnr1kq5x8s8fild9kslg8"; };
} {
  name = "Dates";
  uuid = "ade2ca70-3891-5945-98fb-dc099432e06a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DelimitedFiles";
  uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DiffResults";
  uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5";
  path = "D/DiffResults";
  replaceUrlInManifest = null;
  treehash = "c18e98cba888c6c25d1c3b048e4b3380ca956805";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/DiffResults.jl.git"; rev = "c18e98cba888c6c25d1c3b048e4b3380ca956805"; sha256 = "1w6p3yxajvclax5b9g7cr2jmbc7lvr5nk4gq0aljxdycdq1d2y3v"; };
} {
  name = "DiffRules";
  uuid = "b552c78f-8df3-52c6-915a-8e097449b14b";
  path = "D/DiffRules";
  replaceUrlInManifest = null;
  treehash = "214c3fcac57755cfda163d91c58893a8723f93e9";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/DiffRules.jl.git"; rev = "214c3fcac57755cfda163d91c58893a8723f93e9"; sha256 = "0cwjvj4gma7924fm3yas0nf0jlnwwx4v7fi79ii3s290lkdldzfl"; };
} {
  name = "Distributed";
  uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DocStringExtensions";
  uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae";
  path = "D/DocStringExtensions";
  replaceUrlInManifest = null;
  treehash = "a32185f5428d3986f47c2ab78b1f216d5e6cc96f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDocs/DocStringExtensions.jl.git"; rev = "a32185f5428d3986f47c2ab78b1f216d5e6cc96f"; sha256 = "0fy4kfnfacyfmlly6nqxn77dk2gqw80b69zb4m1i0i39zv3cpqfb"; };
} {
  name = "ExproniconLite";
  uuid = "55351af7-c7e9-48d6-89ff-24e801d99491";
  path = "E/ExproniconLite";
  replaceUrlInManifest = null;
  treehash = "c97ce5069033ac15093dc44222e3ecb0d3af8966";
  artifacts = {};
  src = fetchgit { url = "https://github.com/Roger-luo/ExproniconLite.jl.git"; rev = "c97ce5069033ac15093dc44222e3ecb0d3af8966"; sha256 = "0qk73k71c6v0vsq705mmxfj4vg3qslppxy5c8magaf7v5yr605iv"; };
} {
  name = "FileWatching";
  uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "ForwardDiff";
  uuid = "f6369f11-7733-5829-9624-2563aa707210";
  path = "F/ForwardDiff";
  replaceUrlInManifest = null;
  treehash = "e2af66012e08966366a43251e1fd421522908be6";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/ForwardDiff.jl.git"; rev = "e2af66012e08966366a43251e1fd421522908be6"; sha256 = "1vb46x8mcn61g1l14qrk22c043khg2ml4q1ci7h4k2v34f2ak5fs"; };
} {
  name = "FuzzyCompletions";
  uuid = "fb4132e2-a121-4a70-b8a1-d5b831dcdcc2";
  path = "F/FuzzyCompletions";
  replaceUrlInManifest = null;
  treehash = "9cde086faa37f32794be3d2df393ff064d43cd66";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JunoLab/FuzzyCompletions.jl.git"; rev = "9cde086faa37f32794be3d2df393ff064d43cd66"; sha256 = "07sv88c472n6w4x7diy952igbcfm1s104ysnnvprld83312siw06"; };
} {
  name = "HTTP";
  uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3";
  path = "H/HTTP";
  replaceUrlInManifest = null;
  treehash = "c6a1fff2fd4b1da29d3dccaffb1e1001244d844e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/HTTP.jl.git"; rev = "c6a1fff2fd4b1da29d3dccaffb1e1001244d844e"; sha256 = "1jsyk3mhnwj4h19cxclx26igdqdrw51fd3k1hgav0nm67dy4cxyk"; };
} {
  name = "IniFile";
  uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f";
  path = "I/IniFile";
  replaceUrlInManifest = null;
  treehash = "098e4d2c533924c921f9f9847274f2ad89e018b8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/IniFile.jl.git"; rev = "098e4d2c533924c921f9f9847274f2ad89e018b8"; sha256 = "19cn41w04hikrqdzlxhrgf21rfqhkvj9x1zvwh3yz9hqbf350xs9"; };
} {
  name = "InteractiveUtils";
  uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "IteratorInterfaceExtensions";
  uuid = "82899510-4779-5014-852e-03e436cf321d";
  path = "I/IteratorInterfaceExtensions";
  replaceUrlInManifest = null;
  treehash = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856";
  artifacts = {};
  src = fetchgit { url = "https://github.com/queryverse/IteratorInterfaceExtensions.jl.git"; rev = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"; sha256 = "1slpay1dhja8f9gy6z7b3psgvgcknn963dvfqqakvg1grk9ppa09"; };
} {
  name = "JLLWrappers";
  uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210";
  path = "J/JLLWrappers";
  replaceUrlInManifest = null;
  treehash = "642a199af8b68253517b80bd3bfd17eb4e84df6e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"; rev = "642a199af8b68253517b80bd3bfd17eb4e84df6e"; sha256 = "0v7xhsv9z16d657yp47vgc86ggc01i1wigqh3n0d7i1s84z7xa0h"; };
} {
  name = "LibGit2";
  uuid = "76f85450-5226-5b5a-8eaa-529ad045b433";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libdl";
  uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LinearAlgebra";
  uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LogExpFunctions";
  uuid = "2ab3a3ac-af41-5b50-aa03-7779005ae688";
  path = "L/LogExpFunctions";
  replaceUrlInManifest = null;
  treehash = "7bd5f6565d80b6bf753738d2bc40a5dfea072070";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/LogExpFunctions.jl.git"; rev = "7bd5f6565d80b6bf753738d2bc40a5dfea072070"; sha256 = "0wwl3fjn9k3y07blddwv9jm0zcdmmf3kgm5bh0p9jszpd1sagyfi"; };
} {
  name = "Logging";
  uuid = "56ddb016-857b-54e1-b83d-db4d58db5568";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MacroTools";
  uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09";
  path = "M/MacroTools";
  replaceUrlInManifest = null;
  treehash = "6a8a2a625ab0dea913aba95c11370589e0239ff0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/FluxML/MacroTools.jl.git"; rev = "6a8a2a625ab0dea913aba95c11370589e0239ff0"; sha256 = "0k4z2hyasd9cwxf4l61zk3w4ajs44k69wx6z1ghdn8f5p8xy217f"; };
} {
  name = "Markdown";
  uuid = "d6f4376e-aef5-505a-96c1-9c027394607a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MbedTLS";
  uuid = "739be429-bea8-5141-9913-cc70e7f3736d";
  path = "M/MbedTLS";
  replaceUrlInManifest = null;
  treehash = "1c38e51c3d08ef2278062ebceade0e46cefc96fe";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/MbedTLS.jl.git"; rev = "1c38e51c3d08ef2278062ebceade0e46cefc96fe"; sha256 = "0zjzf2r57l24n3k0gcqkvx3izwn5827iv9ak0lqix0aa5967wvfb"; };
} {
  name = "MbedTLS_jll";
  uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1";
  path = "M/MbedTLS_jll";
  replaceUrlInManifest = null;
  treehash = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6";
  artifacts = {
    "519367e9365948074c1fcc9f4365597f147a5ab7" = [{
      name = "MbedTLS";
      url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.8+0/MbedTLS.v2.16.8.x86_64-linux-gnu.tar.gz";
      sha256 = "5968d98ac1d4fdbf44ed87b0687f916f69ab077961b3cc9ea6068e2d739bd953";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl.git"; rev = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6"; sha256 = "0x43cp26p4w799i1cy4j72l5b1dyqcsab98qjw6yydxk2wha5vw4"; };
} {
  name = "Mmap";
  uuid = "a63ad114-7e13-5084-954f-fe012c677804";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MsgPack";
  uuid = "99f44e22-a591-53d1-9472-aa23ef4bd671";
  path = "M/MsgPack";
  replaceUrlInManifest = null;
  treehash = "a8cbf066b54d793b9a48c5daa5d586cf2b5bd43d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/MsgPack.jl.git"; rev = "a8cbf066b54d793b9a48c5daa5d586cf2b5bd43d"; sha256 = "1layiqjf9si38pfdcszppgcy4zbfqgld7jlw8x645sm9b17b19fg"; };
} {
  name = "NaNMath";
  uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3";
  path = "N/NaNMath";
  replaceUrlInManifest = null;
  treehash = "bfe47e760d60b82b66b61d2d44128b62e3a369fb";
  artifacts = {};
  src = fetchgit { url = "https://github.com/mlubin/NaNMath.jl.git"; rev = "bfe47e760d60b82b66b61d2d44128b62e3a369fb"; sha256 = "1hczhz00qj99w63vp627kwk02l2sr2qmzc2rkwwkdwvzy670p25q"; };
} {
  name = "NetworkOptions";
  uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908";
  path = "N/NetworkOptions";
  replaceUrlInManifest = null;
  treehash = "ed3157f48a05543cce9b241e1f2815f7e843d96e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/NetworkOptions.jl.git"; rev = "ed3157f48a05543cce9b241e1f2815f7e843d96e"; sha256 = "02nm4v67lb1dzhgyyr9bg8kylyyhsgfsxf3nxhbl4hp9dz48an0a"; };
} {
  name = "OpenSpecFun_jll";
  uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e";
  path = "O/OpenSpecFun_jll";
  replaceUrlInManifest = null;
  treehash = "9db77584158d0ab52307f8c04f8e7c08ca76b5b3";
  artifacts = {
    "6b3fe9737f0aeb4ee1b6e63474f6b34d57b6ed31" = [{
      name = "OpenSpecFun";
      url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+3/OpenSpecFun.v0.5.3.x86_64-linux-gnu-libgfortran5.tar.gz";
      sha256 = "78ac48e102326770ed44fb6806d802b65e5557b6e0118b1db2d6f50b70c3384e";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl.git"; rev = "9db77584158d0ab52307f8c04f8e7c08ca76b5b3"; sha256 = "0bl2gcgndsbiwhwy8fl070cjm1fyf9kxj6gkikgirmzgjl29iakn"; };
} {
  name = "OrderedCollections";
  uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d";
  path = "O/OrderedCollections";
  replaceUrlInManifest = null;
  treehash = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/OrderedCollections.jl.git"; rev = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c"; sha256 = "0jaxcmvkp8zpqrz101yikdigz90s70i7in5wn8kybwzf0na3lhwf"; };
} {
  name = "Pkg";
  uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Pluto";
  uuid = "c3e4b0f8-55cb-11ea-2926-15256bba5781";
  path = "null";
  replaceUrlInManifest = "https://github.com/fonsp/Pluto.jl.git";
  treehash = "d410fe096251de52789561ef7a6929f7cca1658e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/fonsp/Pluto.jl.git"; rev = "d410fe096251de52789561ef7a6929f7cca1658e"; sha256 = "1z255riiif30bcvd2wsx36y7h97hy3lk4sdjak315zx28kiav78s"; };
} {
  name = "Preferences";
  uuid = "21216c6a-2e73-6563-6e65-726566657250";
  path = "P/Preferences";
  replaceUrlInManifest = null;
  treehash = "00cfd92944ca9c760982747e9a1d0d5d86ab1e5a";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Preferences.jl.git"; rev = "00cfd92944ca9c760982747e9a1d0d5d86ab1e5a"; sha256 = "1cail43iqzbi6m9v6981rhz47zf2lcvhs5ds5gdqvc9nx5frghxq"; };
} {
  name = "Printf";
  uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "REPL";
  uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Random";
  uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SHA";
  uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce";
  path = "S/SHA";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Serialization";
  uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SharedArrays";
  uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Sockets";
  uuid = "6462fe0b-24de-5631-8697-dd941f90decc";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SparseArrays";
  uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SpecialFunctions";
  uuid = "276daf66-3868-5448-9aa4-cd146d93841b";
  path = "S/SpecialFunctions";
  replaceUrlInManifest = null;
  treehash = "a50550fa3164a8c46747e62063b4d774ac1bcf49";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/SpecialFunctions.jl.git"; rev = "a50550fa3164a8c46747e62063b4d774ac1bcf49"; sha256 = "0viildqh3wfawcan5zy820fa2jfnf3vdb1zsvm8nvi8i6f6mxi9s"; };
} {
  name = "StaticArrays";
  uuid = "90137ffa-7385-5640-81b9-e52037218182";
  path = "S/StaticArrays";
  replaceUrlInManifest = null;
  treehash = "896d55218776ab8f23fb7b222a5a4a946d4aafc2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/StaticArrays.jl.git"; rev = "896d55218776ab8f23fb7b222a5a4a946d4aafc2"; sha256 = "0vvs1kwpax18iyhiivznhq49nid0zh4fbfxyq99h0n3x2s1hzyi6"; };
} {
  name = "Statistics";
  uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "TOML";
  uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76";
  path = "T/TOML";
  replaceUrlInManifest = null;
  treehash = "44aaac2d2aec4a850302f9aa69127c74f0c3787e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/TOML.jl.git"; rev = "44aaac2d2aec4a850302f9aa69127c74f0c3787e"; sha256 = "1xy19fc5lrj9kh298xhczvmjl1cx3p46fj2xlmkisaqxzhd782yd"; };
} {
  name = "TableIOInterface";
  uuid = "d1efa939-5518-4425-949f-ab857e148477";
  path = "T/TableIOInterface";
  replaceUrlInManifest = null;
  treehash = "9a0d3ab8afd14f33a35af7391491ff3104401a35";
  artifacts = {};
  src = fetchgit { url = "https://github.com/lungben/TableIOInterface.jl.git"; rev = "9a0d3ab8afd14f33a35af7391491ff3104401a35"; sha256 = "0p2fi9jbyfg2j6rysv4if7dx8qw2mssb04i75j1zq607j8707kvn"; };
} {
  name = "TableTraits";
  uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c";
  path = "T/TableTraits";
  replaceUrlInManifest = null;
  treehash = "c06b2f539df1c6efa794486abfb6ed2022561a39";
  artifacts = {};
  src = fetchgit { url = "https://github.com/queryverse/TableTraits.jl.git"; rev = "c06b2f539df1c6efa794486abfb6ed2022561a39"; sha256 = "08ssb2630wm6j8f2qa985mn2vfibfm5kjcn4ayl2qkhfcyp8daw4"; };
} {
  name = "Tables";
  uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c";
  path = "T/Tables";
  replaceUrlInManifest = null;
  treehash = "8ed4a3ea724dac32670b062be3ef1c1de6773ae8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Tables.jl.git"; rev = "8ed4a3ea724dac32670b062be3ef1c1de6773ae8"; sha256 = "1sqqagzqvav8b1rv5ywwbgy9ixvlmipq95fkwfwn0m8769i8jwzb"; };
} {
  name = "Test";
  uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "URIs";
  uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4";
  path = "U/URIs";
  replaceUrlInManifest = null;
  treehash = "97bbe755a53fe859669cd907f2d96aee8d2c1355";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/URIs.jl.git"; rev = "97bbe755a53fe859669cd907f2d96aee8d2c1355"; sha256 = "0kp4hg3kknkm2smlcizqfd33l9x4vkahc2714gnbjp39fj285b92"; };
} {
  name = "UUIDs";
  uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Unicode";
  uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
}];
}
