# This file is autogenerated, do not edit by hand!
{fetchgit}: {
  registryUrl = "https://github.com/JuliaRegistries/General.git";
  registryRev = "9f433a0b0e324ff16512434acf72984b72e629d7";
  registrySha256 = "1hfch6pg1sgd6sywjmx07zbdzxgsizj83qaq61l59h4d8wfp5chk";
  rootPackages = ["Pluto" "PlutoBindServer" "PlutoUtils"];
  closure = [{
  name = "Artifacts";
  uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33";
  path = "A/Artifacts";
  replaceUrlInManifest = null;
  treehash = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Artifacts.jl.git"; rev = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744"; sha256 = "0i0s26ypiwg6zyb3aqn9kiyiblkkab1mfac9plmq2jv4hggm4jfc"; };
} {
  name = "Base64";
  uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DataAPI";
  uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a";
  path = "D/DataAPI";
  replaceUrlInManifest = null;
  treehash = "8ab70b4de35bb3b8cc19654f6b893cf5164f8ee8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/DataAPI.jl.git"; rev = "8ab70b4de35bb3b8cc19654f6b893cf5164f8ee8"; sha256 = "0p7v12sjq87p9vl7ij8f4cmg61h4b0fn6ixbqxji746360jh0iah"; };
} {
  name = "DataValueInterfaces";
  uuid = "e2d170a0-9d28-54be-80f0-106bbe20a464";
  path = "D/DataValueInterfaces";
  replaceUrlInManifest = null;
  treehash = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6";
  artifacts = {};
  src = fetchgit { url = "https://github.com/queryverse/DataValueInterfaces.jl.git"; rev = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"; sha256 = "0g2wj6q7jj956nx6g7dk8x7w1c4l2xcmnr1kq5x8s8fild9kslg8"; };
} {
  name = "Dates";
  uuid = "ade2ca70-3891-5945-98fb-dc099432e06a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Distributed";
  uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "FuzzyCompletions";
  uuid = "fb4132e2-a121-4a70-b8a1-d5b831dcdcc2";
  path = "F/FuzzyCompletions";
  replaceUrlInManifest = null;
  treehash = "5ca3ddf3061771d25d1699ce53a80a39300811e3";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JunoLab/FuzzyCompletions.jl.git"; rev = "5ca3ddf3061771d25d1699ce53a80a39300811e3"; sha256 = "1ncfjhsr6biv0k1xvsr2g0ay9mx9y98xchgikidwi4nhzw3g2j0f"; };
} {
  name = "GitHubActions";
  uuid = "6b79fd1a-b13a-48ab-b6b0-aaee1fee41df";
  path = "G/GitHubActions";
  replaceUrlInManifest = null;
  treehash = "7dfdc3539f8585af057eca74ba2455f697fb4eec";
  artifacts = {};
  src = fetchgit { url = "https://github.com/julia-actions/GitHubActions.jl.git"; rev = "7dfdc3539f8585af057eca74ba2455f697fb4eec"; sha256 = "1hhffhz1fm3vclnh1cxkxv8bpdj9sgk3kn6zcf51vbc3k4avqp6s"; };
} {
  name = "HTTP";
  uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3";
  path = "H/HTTP";
  replaceUrlInManifest = null;
  treehash = "63055ee44b5c2b95ec1921edcf856c60124ff0c3";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/HTTP.jl.git"; rev = "63055ee44b5c2b95ec1921edcf856c60124ff0c3"; sha256 = "0ij0yci13c46p92m4zywvcs02nn8pm0abyfffiyhxvva6hq48lyl"; };
} {
  name = "IniFile";
  uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f";
  path = "I/IniFile";
  replaceUrlInManifest = null;
  treehash = "098e4d2c533924c921f9f9847274f2ad89e018b8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/IniFile.jl.git"; rev = "098e4d2c533924c921f9f9847274f2ad89e018b8"; sha256 = "19cn41w04hikrqdzlxhrgf21rfqhkvj9x1zvwh3yz9hqbf350xs9"; };
} {
  name = "InteractiveUtils";
  uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "IteratorInterfaceExtensions";
  uuid = "82899510-4779-5014-852e-03e436cf321d";
  path = "I/IteratorInterfaceExtensions";
  replaceUrlInManifest = null;
  treehash = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856";
  artifacts = {};
  src = fetchgit { url = "https://github.com/queryverse/IteratorInterfaceExtensions.jl.git"; rev = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"; sha256 = "1slpay1dhja8f9gy6z7b3psgvgcknn963dvfqqakvg1grk9ppa09"; };
} {
  name = "JLLWrappers";
  uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210";
  path = "J/JLLWrappers";
  replaceUrlInManifest = null;
  treehash = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"; rev = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0"; sha256 = "1sj3mi2dcc13apqfpy401wic5n0pgbck1p98b2g3zw0mln9s83m4"; };
} {
  name = "JSON";
  uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6";
  path = "J/JSON";
  replaceUrlInManifest = null;
  treehash = "81690084b6198a2e1da36fcfda16eeca9f9f24e4";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/JSON.jl.git"; rev = "81690084b6198a2e1da36fcfda16eeca9f9f24e4"; sha256 = "1f9k613kbknmp4fgjxvjaw4d5sfbx8a5hmcszmp1w9rqfqngjx9m"; };
} {
  name = "LibGit2";
  uuid = "76f85450-5226-5b5a-8eaa-529ad045b433";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libdl";
  uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LinearAlgebra";
  uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Logging";
  uuid = "56ddb016-857b-54e1-b83d-db4d58db5568";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Markdown";
  uuid = "d6f4376e-aef5-505a-96c1-9c027394607a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MbedTLS";
  uuid = "739be429-bea8-5141-9913-cc70e7f3736d";
  path = "M/MbedTLS";
  replaceUrlInManifest = null;
  treehash = "1c38e51c3d08ef2278062ebceade0e46cefc96fe";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/MbedTLS.jl.git"; rev = "1c38e51c3d08ef2278062ebceade0e46cefc96fe"; sha256 = "0zjzf2r57l24n3k0gcqkvx3izwn5827iv9ak0lqix0aa5967wvfb"; };
} {
  name = "MbedTLS_jll";
  uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1";
  path = "M/MbedTLS_jll";
  replaceUrlInManifest = null;
  treehash = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6";
  artifacts = {
    "519367e9365948074c1fcc9f4365597f147a5ab7" = [{
      name = "MbedTLS";
      url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.8+0/MbedTLS.v2.16.8.x86_64-linux-gnu.tar.gz";
      sha256 = "5968d98ac1d4fdbf44ed87b0687f916f69ab077961b3cc9ea6068e2d739bd953";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl.git"; rev = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6"; sha256 = "0x43cp26p4w799i1cy4j72l5b1dyqcsab98qjw6yydxk2wha5vw4"; };
} {
  name = "Mmap";
  uuid = "a63ad114-7e13-5084-954f-fe012c677804";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MsgPack";
  uuid = "99f44e22-a591-53d1-9472-aa23ef4bd671";
  path = "M/MsgPack";
  replaceUrlInManifest = null;
  treehash = "a8cbf066b54d793b9a48c5daa5d586cf2b5bd43d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/MsgPack.jl.git"; rev = "a8cbf066b54d793b9a48c5daa5d586cf2b5bd43d"; sha256 = "1layiqjf9si38pfdcszppgcy4zbfqgld7jlw8x645sm9b17b19fg"; };
} {
  name = "Parsers";
  uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0";
  path = "P/Parsers";
  replaceUrlInManifest = null;
  treehash = "50c9a9ed8c714945e01cd53a21007ed3865ed714";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Parsers.jl.git"; rev = "50c9a9ed8c714945e01cd53a21007ed3865ed714"; sha256 = "16iffl6l28kspgqch48mhi1s8qhspr3cpqcwsph3rqi72lbfqygx"; };
} {
  name = "Pkg";
  uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Pluto";
  uuid = "c3e4b0f8-55cb-11ea-2926-15256bba5781";
  path = "null";
  replaceUrlInManifest = "https://github.com/fonsp/Pluto.jl";
  treehash = "7a7e8704e927da7e557c24aba67ca8feb6bc7a9f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/fonsp/Pluto.jl"; rev = "7a7e8704e927da7e557c24aba67ca8feb6bc7a9f"; sha256 = "0zfzq172di3lzawqs0w58fb83lagx8prbwpyry8dc156ki0fda6l"; };
} {
  name = "PlutoBindServer";
  uuid = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4";
  path = "null";
  replaceUrlInManifest = "https://github.com/JuliaPluto/PlutoBindServer.jl";
  treehash = "f38a7a3808ebe8e9fb580ddcc55b39298bd8fdb1";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPluto/PlutoBindServer.jl"; rev = "f38a7a3808ebe8e9fb580ddcc55b39298bd8fdb1"; sha256 = "0lij7dxqjfq3s2x4a84l9zhs7qwqjg6vf3p21jsdzvfzpay3kcff"; };
} {
  name = "PlutoUtils";
  uuid = "a5ec66cb-57bb-4ae5-9259-3342d9ed6c94";
  path = "null";
  replaceUrlInManifest = "https://github.com/fonsp/PlutoUtils.jl";
  treehash = "57d86daaac097283f05e57b74e5356f67bec4f79";
  artifacts = {};
  src = fetchgit { url = "https://github.com/fonsp/PlutoUtils.jl"; rev = "57d86daaac097283f05e57b74e5356f67bec4f79"; sha256 = "0j6psk7clqrvyp7cig8i8brspzj3yqpf1sh5grjjwr1izq7mj60y"; };
} {
  name = "Printf";
  uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "REPL";
  uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Random";
  uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SHA";
  uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce";
  path = "S/SHA";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Serialization";
  uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Sockets";
  uuid = "6462fe0b-24de-5631-8697-dd941f90decc";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "TableIOInterface";
  uuid = "d1efa939-5518-4425-949f-ab857e148477";
  path = "T/TableIOInterface";
  replaceUrlInManifest = null;
  treehash = "9a0d3ab8afd14f33a35af7391491ff3104401a35";
  artifacts = {};
  src = fetchgit { url = "https://github.com/lungben/TableIOInterface.jl.git"; rev = "9a0d3ab8afd14f33a35af7391491ff3104401a35"; sha256 = "0p2fi9jbyfg2j6rysv4if7dx8qw2mssb04i75j1zq607j8707kvn"; };
} {
  name = "TableTraits";
  uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c";
  path = "T/TableTraits";
  replaceUrlInManifest = null;
  treehash = "b1ad568ba658d8cbb3b892ed5380a6f3e781a81e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/queryverse/TableTraits.jl.git"; rev = "b1ad568ba658d8cbb3b892ed5380a6f3e781a81e"; sha256 = "0lzb9xqnhgjbvkscc4p9vw3pzajm3a5a6ayv6byqc53ws8fxqk2v"; };
} {
  name = "Tables";
  uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c";
  path = "T/Tables";
  replaceUrlInManifest = null;
  treehash = "a716dde43d57fa537a19058d044b495301ba6565";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Tables.jl.git"; rev = "a716dde43d57fa537a19058d044b495301ba6565"; sha256 = "1265ak3gxxf1rx2rzj40jc9s6972x2v8ncm7qign1irr54knj8v6"; };
} {
  name = "Test";
  uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "URIs";
  uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4";
  path = "U/URIs";
  replaceUrlInManifest = null;
  treehash = "7855809b88d7b16e9b029afd17880930626f54a2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/URIs.jl.git"; rev = "7855809b88d7b16e9b029afd17880930626f54a2"; sha256 = "0fqyagsqks5za7m0czafr34m2xh5501f689k9cn5x3npajdnh2r3"; };
} {
  name = "UUIDs";
  uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Unicode";
  uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
}];
}
