((nil . ((julia-program . "julia-bin")
         (julia-snail-executable . "julia")
         (inferior-julia-program-name . "julia-bin")
         (set-popup-rule! "^\\*julia" :side 'right :size 45 :quit nil :select nil :ttl 0)
         )))
