((nil .  ((setq-local inferior-julia-program-name "julia-bin")
          (setq-local julia-program "julia-bin")
          (setq-local org-babel-julia-command "julia-bin")
          (setq-local julia-snail-executable "~/ghq/github.com/GTrunSec/my-julia2nix-env/bin/julia")
                    )))
