[devshell]
packages = [ "julia_16-bin" ]
[[commands]]
name = "pluto"
category = "Julia Package"
command = '''
        eval $(echo "julia -e 'import Pkg; Pkg.activate(\".\"); using Pluto; Pluto.run(host=\"$1\", port=$2)'")
        '''
help = "launch pluto server: pluto <ip> <port>"


[[commands]]
name = "addPackage"
category = "Julia Package"
command = '''
        eval $(echo "julia -e 'using Pkg; Pkg.activate(\"$1\"); Pkg.add([$2])'")
        '''
help = "Exp: addPackage . '\"StatsFuns, Images\"' -> <activatePath> <Package Name List>"

[[env]]
name = "JULIA_DEPOT_PATH"
value = "./.julia_depot"

# [[env]]
# name = "PATH"
# prefix = "bin"
