# This file is autogenerated, do not edit by hand!
{fetchgit}: {
  registryUrl = "https://github.com/JuliaRegistries/General.git";
  registryRev = "f98d2361466bf7ed380bb692c565f6a5e39689ce";
  registrySha256 = "1k3rrghdwwzc76d47d0phm3cgg66vj2g36qbhp9mzrvwcm4cfsis";
  rootPackages = ["Distributions" "FFTW" "ForwardDiff" "Optim" "Pluto" "StatsFuns"];
  closure = [{
  name = "AbstractFFTs";
  uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c";
  path = "A/AbstractFFTs";
  replaceUrlInManifest = null;
  treehash = "485ee0867925449198280d4af84bdb46a2a404d0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/AbstractFFTs.jl.git"; rev = "485ee0867925449198280d4af84bdb46a2a404d0"; sha256 = "0083pwdyxjb04i330ir9pc8kmp4bwk59lx1jgc9qi05y8j7xzbp0"; };
} {
  name = "ArrayInterface";
  uuid = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9";
  path = "A/ArrayInterface";
  replaceUrlInManifest = null;
  treehash = "e7edcc1ac140cce87b7442ff0fa88b5f19fb71fa";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/ArrayInterface.jl.git"; rev = "e7edcc1ac140cce87b7442ff0fa88b5f19fb71fa"; sha256 = "07jv2hpr8nz9j6vxf6iyrqls94hb9b5nc7r763i9j15gbrw3426f"; };
} {
  name = "Artifacts";
  uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33";
  path = "A/Artifacts";
  replaceUrlInManifest = null;
  treehash = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Artifacts.jl.git"; rev = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744"; sha256 = "0i0s26ypiwg6zyb3aqn9kiyiblkkab1mfac9plmq2jv4hggm4jfc"; };
} {
  name = "Base64";
  uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "ChainRulesCore";
  uuid = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4";
  path = "C/ChainRulesCore";
  replaceUrlInManifest = null;
  treehash = "de4f08843c332d355852721adb1592bce7924da3";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/ChainRulesCore.jl.git"; rev = "de4f08843c332d355852721adb1592bce7924da3"; sha256 = "1k0iayw39n1ikkkhvyi4498vsnzc94skqs41gnd15632gxjfvki4"; };
} {
  name = "CommonSubexpressions";
  uuid = "bbf7d656-a473-5ed7-a52c-81e309532950";
  path = "C/CommonSubexpressions";
  replaceUrlInManifest = null;
  treehash = "7b8a93dba8af7e3b42fecabf646260105ac373f7";
  artifacts = {};
  src = fetchgit { url = "https://github.com/rdeits/CommonSubexpressions.jl.git"; rev = "7b8a93dba8af7e3b42fecabf646260105ac373f7"; sha256 = "0mgy90kk8ksv3l720kkk04gnhn4aqhh2dj4sp3x8yy3limngfjay"; };
} {
  name = "Compat";
  uuid = "34da2185-b29b-5c13-b0c7-acf172513d20";
  path = "C/Compat";
  replaceUrlInManifest = null;
  treehash = "919c7f3151e79ff196add81d7f4e45d91bbf420b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/Compat.jl.git"; rev = "919c7f3151e79ff196add81d7f4e45d91bbf420b"; sha256 = "1m4r5i8mq29xjp3mllh6047n5a78sdyld57m15anrnsjgaapcgby"; };
} {
  name = "CompilerSupportLibraries_jll";
  uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae";
  path = "C/CompilerSupportLibraries_jll";
  replaceUrlInManifest = null;
  treehash = "8e695f735fca77e9708e795eda62afdb869cbb70";
  artifacts = {
    "424e8fcc25b26b5599a8d0f73dd5e8cac598fca8" = [{
      name = "CompilerSupportLibraries";
      url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.3+0/CompilerSupportLibraries.v0.3.3.x86_64-linux-gnu-libgfortran5.tar.gz";
      sha256 = "23771ec6d2fa014db480b5cfe8e1b6f34b2d29e8bbea8cdce1edd5f1e15cb6e0";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl.git"; rev = "8e695f735fca77e9708e795eda62afdb869cbb70"; sha256 = "0iqm61cjxilqcapz9z9w42qq799dmzfd92px2gysjdmny3v0qf4r"; };
} {
  name = "DataAPI";
  uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a";
  path = "D/DataAPI";
  replaceUrlInManifest = null;
  treehash = "dfb3b7e89e395be1e25c2ad6d7690dc29cc53b1d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/DataAPI.jl.git"; rev = "dfb3b7e89e395be1e25c2ad6d7690dc29cc53b1d"; sha256 = "14sfvkz169zcbap3gdwpj16qsap783h86fd07flfxk822abam11w"; };
} {
  name = "DataStructures";
  uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8";
  path = "D/DataStructures";
  replaceUrlInManifest = null;
  treehash = "4437b64df1e0adccc3e5d1adbc3ac741095e4677";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/DataStructures.jl.git"; rev = "4437b64df1e0adccc3e5d1adbc3ac741095e4677"; sha256 = "0hdqp8ipsqdw5bqqkdvz4j6n67x80sj5azr9vzyxwjfsgkfbnk2l"; };
} {
  name = "DataValueInterfaces";
  uuid = "e2d170a0-9d28-54be-80f0-106bbe20a464";
  path = "D/DataValueInterfaces";
  replaceUrlInManifest = null;
  treehash = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6";
  artifacts = {};
  src = fetchgit { url = "https://github.com/queryverse/DataValueInterfaces.jl.git"; rev = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"; sha256 = "0g2wj6q7jj956nx6g7dk8x7w1c4l2xcmnr1kq5x8s8fild9kslg8"; };
} {
  name = "Dates";
  uuid = "ade2ca70-3891-5945-98fb-dc099432e06a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DelimitedFiles";
  uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DiffResults";
  uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5";
  path = "D/DiffResults";
  replaceUrlInManifest = null;
  treehash = "c18e98cba888c6c25d1c3b048e4b3380ca956805";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/DiffResults.jl.git"; rev = "c18e98cba888c6c25d1c3b048e4b3380ca956805"; sha256 = "1w6p3yxajvclax5b9g7cr2jmbc7lvr5nk4gq0aljxdycdq1d2y3v"; };
} {
  name = "DiffRules";
  uuid = "b552c78f-8df3-52c6-915a-8e097449b14b";
  path = "D/DiffRules";
  replaceUrlInManifest = null;
  treehash = "214c3fcac57755cfda163d91c58893a8723f93e9";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/DiffRules.jl.git"; rev = "214c3fcac57755cfda163d91c58893a8723f93e9"; sha256 = "0cwjvj4gma7924fm3yas0nf0jlnwwx4v7fi79ii3s290lkdldzfl"; };
} {
  name = "Distributed";
  uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Distributions";
  uuid = "31c24e10-a181-5473-b8eb-7969acd0382f";
  path = "D/Distributions";
  replaceUrlInManifest = null;
  treehash = "e64debe8cd174cc52d7dd617ebc5492c6f8b698c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/Distributions.jl.git"; rev = "e64debe8cd174cc52d7dd617ebc5492c6f8b698c"; sha256 = "1y7an0xxfly11w6hck0kav417l8gdzcm2zk7xyb0w3bk6dvgivgb"; };
} {
  name = "FFTW";
  uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341";
  path = "F/FFTW";
  replaceUrlInManifest = null;
  treehash = "1b48dbde42f307e48685fa9213d8b9f8c0d87594";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/FFTW.jl.git"; rev = "1b48dbde42f307e48685fa9213d8b9f8c0d87594"; sha256 = "1xgqy9zl9sw1bh5fgsh59dc9aafpp76zjlj99hjzq025n02z5nly"; };
} {
  name = "FFTW_jll";
  uuid = "f5851436-0d7a-5f13-b9de-f02708fd171a";
  path = "F/FFTW_jll";
  replaceUrlInManifest = null;
  treehash = "5a0d4b6a22a34d17d53543bd124f4b08ed78e8b0";
  artifacts = {
    "81791030d1dcd08bf0c67b3e8224cb573d0f5a0a" = [{
      name = "FFTW";
      url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+7/FFTW.v3.3.9.x86_64-linux-gnu.tar.gz";
      sha256 = "4b1202c3acbaf05b5f7288fdf6a901f8ee7da49feaa53a04e7a9af5d10a6a51c";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl.git"; rev = "5a0d4b6a22a34d17d53543bd124f4b08ed78e8b0"; sha256 = "07qzcvhandsxl5hn0bxy1jv1ji2m70kxw3683vd8r3zdqq6swdf6"; };
} {
  name = "FillArrays";
  uuid = "1a297f60-69ca-5386-bcde-b61e274b549b";
  path = "F/FillArrays";
  replaceUrlInManifest = null;
  treehash = "4705cc4e212c3c978c60b1b18118ec49b4d731fd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/FillArrays.jl.git"; rev = "4705cc4e212c3c978c60b1b18118ec49b4d731fd"; sha256 = "1cbyynlkvlgp9rkcz5xl6pkh6l5nj84i005qc9w49bxll00pjnrp"; };
} {
  name = "FiniteDiff";
  uuid = "6a86dc24-6348-571c-b903-95158fe2bd41";
  path = "F/FiniteDiff";
  replaceUrlInManifest = null;
  treehash = "f6f80c8f934efd49a286bb5315360be66956dfc4";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/FiniteDiff.jl.git"; rev = "f6f80c8f934efd49a286bb5315360be66956dfc4"; sha256 = "0ndazn02wn8ddwgjh1i32y7pbaqpw06f42ccilz5ya78cyrjhq2m"; };
} {
  name = "ForwardDiff";
  uuid = "f6369f11-7733-5829-9624-2563aa707210";
  path = "F/ForwardDiff";
  replaceUrlInManifest = null;
  treehash = "d48a40c0f54f29a5c8748cfb3225719accc72b77";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/ForwardDiff.jl.git"; rev = "d48a40c0f54f29a5c8748cfb3225719accc72b77"; sha256 = "1bm16q2pi743sfw475snjfnjwg1p0c5vl1ipws6kain99hpxr7w3"; };
} {
  name = "FuzzyCompletions";
  uuid = "fb4132e2-a121-4a70-b8a1-d5b831dcdcc2";
  path = "F/FuzzyCompletions";
  replaceUrlInManifest = null;
  treehash = "5ca3ddf3061771d25d1699ce53a80a39300811e3";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JunoLab/FuzzyCompletions.jl.git"; rev = "5ca3ddf3061771d25d1699ce53a80a39300811e3"; sha256 = "1ncfjhsr6biv0k1xvsr2g0ay9mx9y98xchgikidwi4nhzw3g2j0f"; };
} {
  name = "HTTP";
  uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3";
  path = "H/HTTP";
  replaceUrlInManifest = null;
  treehash = "c9f380c76d8aaa1fa7ea9cf97bddbc0d5b15adc2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/HTTP.jl.git"; rev = "c9f380c76d8aaa1fa7ea9cf97bddbc0d5b15adc2"; sha256 = "1qb4dr85w2f9fqzilm7wmr9nbihmsli92fmwafwfsg79bqnb45qh"; };
} {
  name = "IfElse";
  uuid = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173";
  path = "I/IfElse";
  replaceUrlInManifest = null;
  treehash = "28e837ff3e7a6c3cdb252ce49fb412c8eb3caeef";
  artifacts = {};
  src = fetchgit { url = "https://github.com/SciML/IfElse.jl.git"; rev = "28e837ff3e7a6c3cdb252ce49fb412c8eb3caeef"; sha256 = "1wrw842r8708fryf2ihp9mkmdrg27saa9nix2c31vs995k2fgr9w"; };
} {
  name = "IniFile";
  uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f";
  path = "I/IniFile";
  replaceUrlInManifest = null;
  treehash = "098e4d2c533924c921f9f9847274f2ad89e018b8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/IniFile.jl.git"; rev = "098e4d2c533924c921f9f9847274f2ad89e018b8"; sha256 = "19cn41w04hikrqdzlxhrgf21rfqhkvj9x1zvwh3yz9hqbf350xs9"; };
} {
  name = "IntelOpenMP_jll";
  uuid = "1d5cc7b8-4909-519e-a0f8-d0f5ad9712d0";
  path = "I/IntelOpenMP_jll";
  replaceUrlInManifest = null;
  treehash = "d979e54b71da82f3a65b62553da4fc3d18c9004c";
  artifacts = {
    "947793e42b663bacd09f00d96aa96a47095f3b1c" = [{
      name = "IntelOpenMP";
      url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2018.0.3+2/IntelOpenMP.v2018.0.3.x86_64-linux-gnu.tar.gz";
      sha256 = "f40e3d5f625eb5ba907c9b73fd8d4adf5e74dadbc0022f5be2185e93228d0703";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl.git"; rev = "d979e54b71da82f3a65b62553da4fc3d18c9004c"; sha256 = "0gwxfmd1vrn1bjdivm7yjpwsjmw79cp7mirjiv8pr6xva1h3l3g7"; };
} {
  name = "InteractiveUtils";
  uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "IteratorInterfaceExtensions";
  uuid = "82899510-4779-5014-852e-03e436cf321d";
  path = "I/IteratorInterfaceExtensions";
  replaceUrlInManifest = null;
  treehash = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856";
  artifacts = {};
  src = fetchgit { url = "https://github.com/queryverse/IteratorInterfaceExtensions.jl.git"; rev = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"; sha256 = "1slpay1dhja8f9gy6z7b3psgvgcknn963dvfqqakvg1grk9ppa09"; };
} {
  name = "JLLWrappers";
  uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210";
  path = "J/JLLWrappers";
  replaceUrlInManifest = null;
  treehash = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"; rev = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0"; sha256 = "1sj3mi2dcc13apqfpy401wic5n0pgbck1p98b2g3zw0mln9s83m4"; };
} {
  name = "LazyArtifacts";
  uuid = "4af54fe1-eca0-43a8-85a7-787d91b784e3";
  path = "L/LazyArtifacts";
  replaceUrlInManifest = null;
  treehash = "4bb5499a1fc437342ea9ab7e319ede5a457c0968";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/LazyArtifacts.jl.git"; rev = "4bb5499a1fc437342ea9ab7e319ede5a457c0968"; sha256 = "0qln5pq2zm68wgm104cxyviiql8xkv7rf68hivar2b7x2a8vwnk0"; };
} {
  name = "LibGit2";
  uuid = "76f85450-5226-5b5a-8eaa-529ad045b433";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libdl";
  uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LineSearches";
  uuid = "d3d80556-e9d4-5f37-9878-2ab0fcc64255";
  path = "L/LineSearches";
  replaceUrlInManifest = null;
  treehash = "f27132e551e959b3667d8c93eae90973225032dd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaNLSolvers/LineSearches.jl.git"; rev = "f27132e551e959b3667d8c93eae90973225032dd"; sha256 = "1qc4la07w6s1xhcyd0hvbnpr31zc1a2ssgyybc8biv5m00g0dnr0"; };
} {
  name = "LinearAlgebra";
  uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Logging";
  uuid = "56ddb016-857b-54e1-b83d-db4d58db5568";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MKL_jll";
  uuid = "856f044c-d86e-5d09-b602-aeab76dc8ba7";
  path = "M/MKL_jll";
  replaceUrlInManifest = null;
  treehash = "c253236b0ed414624b083e6b72bfe891fbd2c7af";
  artifacts = {
    "a8e009985328801a84c9af6610f94f77a7c12852" = [{
      name = "MKL";
      url = "https://github.com/JuliaBinaryWrappers/MKL_jll.jl/releases/download/MKL-v2021.1.1+1/MKL.v2021.1.1.x86_64-linux-gnu.tar.gz";
      sha256 = "70800f6e75e8ac3a0ff66069bec20ef410e9b240ef4a0f3b96cbbab3df81700f";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/MKL_jll.jl.git"; rev = "c253236b0ed414624b083e6b72bfe891fbd2c7af"; sha256 = "1h3z0jid9wjz7if0qh54f200nyb17gc6cw1l66dljr0b6zgxj3zy"; };
} {
  name = "MacroTools";
  uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09";
  path = "M/MacroTools";
  replaceUrlInManifest = null;
  treehash = "6a8a2a625ab0dea913aba95c11370589e0239ff0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/FluxML/MacroTools.jl.git"; rev = "6a8a2a625ab0dea913aba95c11370589e0239ff0"; sha256 = "0k4z2hyasd9cwxf4l61zk3w4ajs44k69wx6z1ghdn8f5p8xy217f"; };
} {
  name = "Markdown";
  uuid = "d6f4376e-aef5-505a-96c1-9c027394607a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MbedTLS";
  uuid = "739be429-bea8-5141-9913-cc70e7f3736d";
  path = "M/MbedTLS";
  replaceUrlInManifest = null;
  treehash = "1c38e51c3d08ef2278062ebceade0e46cefc96fe";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/MbedTLS.jl.git"; rev = "1c38e51c3d08ef2278062ebceade0e46cefc96fe"; sha256 = "0zjzf2r57l24n3k0gcqkvx3izwn5827iv9ak0lqix0aa5967wvfb"; };
} {
  name = "MbedTLS_jll";
  uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1";
  path = "M/MbedTLS_jll";
  replaceUrlInManifest = null;
  treehash = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6";
  artifacts = {
    "519367e9365948074c1fcc9f4365597f147a5ab7" = [{
      name = "MbedTLS";
      url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.8+0/MbedTLS.v2.16.8.x86_64-linux-gnu.tar.gz";
      sha256 = "5968d98ac1d4fdbf44ed87b0687f916f69ab077961b3cc9ea6068e2d739bd953";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl.git"; rev = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6"; sha256 = "0x43cp26p4w799i1cy4j72l5b1dyqcsab98qjw6yydxk2wha5vw4"; };
} {
  name = "Missings";
  uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28";
  path = "M/Missings";
  replaceUrlInManifest = null;
  treehash = "f8c673ccc215eb50fcadb285f522420e29e69e1c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Missings.jl.git"; rev = "f8c673ccc215eb50fcadb285f522420e29e69e1c"; sha256 = "1qsnvpmqrps631yvka11hb5jcsfskgpn29c99fvm73vd9xqp6cin"; };
} {
  name = "Mmap";
  uuid = "a63ad114-7e13-5084-954f-fe012c677804";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MsgPack";
  uuid = "99f44e22-a591-53d1-9472-aa23ef4bd671";
  path = "M/MsgPack";
  replaceUrlInManifest = null;
  treehash = "a8cbf066b54d793b9a48c5daa5d586cf2b5bd43d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/MsgPack.jl.git"; rev = "a8cbf066b54d793b9a48c5daa5d586cf2b5bd43d"; sha256 = "1layiqjf9si38pfdcszppgcy4zbfqgld7jlw8x645sm9b17b19fg"; };
} {
  name = "NLSolversBase";
  uuid = "d41bc354-129a-5804-8e4c-c37616107c6c";
  path = "N/NLSolversBase";
  replaceUrlInManifest = null;
  treehash = "39d6bc45e99c96e6995cbddac02877f9b61a1dd1";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaNLSolvers/NLSolversBase.jl.git"; rev = "39d6bc45e99c96e6995cbddac02877f9b61a1dd1"; sha256 = "05k4p05j1qmszxa7igngbvm0pszgrf8ikdjb1qjq6w7c4yh2ak8b"; };
} {
  name = "NaNMath";
  uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3";
  path = "N/NaNMath";
  replaceUrlInManifest = null;
  treehash = "bfe47e760d60b82b66b61d2d44128b62e3a369fb";
  artifacts = {};
  src = fetchgit { url = "https://github.com/mlubin/NaNMath.jl.git"; rev = "bfe47e760d60b82b66b61d2d44128b62e3a369fb"; sha256 = "1hczhz00qj99w63vp627kwk02l2sr2qmzc2rkwwkdwvzy670p25q"; };
} {
  name = "NetworkOptions";
  uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908";
  path = "N/NetworkOptions";
  replaceUrlInManifest = null;
  treehash = "ed3157f48a05543cce9b241e1f2815f7e843d96e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/NetworkOptions.jl.git"; rev = "ed3157f48a05543cce9b241e1f2815f7e843d96e"; sha256 = "02nm4v67lb1dzhgyyr9bg8kylyyhsgfsxf3nxhbl4hp9dz48an0a"; };
} {
  name = "OpenSpecFun_jll";
  uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e";
  path = "O/OpenSpecFun_jll";
  replaceUrlInManifest = null;
  treehash = "9db77584158d0ab52307f8c04f8e7c08ca76b5b3";
  artifacts = {
    "6b3fe9737f0aeb4ee1b6e63474f6b34d57b6ed31" = [{
      name = "OpenSpecFun";
      url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+3/OpenSpecFun.v0.5.3.x86_64-linux-gnu-libgfortran5.tar.gz";
      sha256 = "78ac48e102326770ed44fb6806d802b65e5557b6e0118b1db2d6f50b70c3384e";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl.git"; rev = "9db77584158d0ab52307f8c04f8e7c08ca76b5b3"; sha256 = "0bl2gcgndsbiwhwy8fl070cjm1fyf9kxj6gkikgirmzgjl29iakn"; };
} {
  name = "Optim";
  uuid = "429524aa-4258-5aef-a3af-852621145aeb";
  path = "O/Optim";
  replaceUrlInManifest = null;
  treehash = "3286df38aba45acf7445f3acd87b7b57b7c7feb7";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaNLSolvers/Optim.jl.git"; rev = "3286df38aba45acf7445f3acd87b7b57b7c7feb7"; sha256 = "0h68n3mlblxyszramnjpkinr4l49jzqv0kyy5nlabl0nwv1c1bw2"; };
} {
  name = "OrderedCollections";
  uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d";
  path = "O/OrderedCollections";
  replaceUrlInManifest = null;
  treehash = "4fa2ba51070ec13fcc7517db714445b4ab986bdf";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/OrderedCollections.jl.git"; rev = "4fa2ba51070ec13fcc7517db714445b4ab986bdf"; sha256 = "1mc0q32mcgawc9161xrpnrsrrn6jli1rhfbslv4f4fii94q78wd4"; };
} {
  name = "PDMats";
  uuid = "90014a1f-27ba-587c-ab20-58faa44d9150";
  path = "P/PDMats";
  replaceUrlInManifest = null;
  treehash = "f82a0e71f222199de8e9eb9a09977bd0767d52a0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/PDMats.jl.git"; rev = "f82a0e71f222199de8e9eb9a09977bd0767d52a0"; sha256 = "1gyhfjmb0qlqgx2398b356cph25bnpjagcslckv41bzyf8pg3ybl"; };
} {
  name = "Parameters";
  uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a";
  path = "P/Parameters";
  replaceUrlInManifest = null;
  treehash = "2276ac65f1e236e0a6ea70baff3f62ad4c625345";
  artifacts = {};
  src = fetchgit { url = "https://github.com/mauro3/Parameters.jl.git"; rev = "2276ac65f1e236e0a6ea70baff3f62ad4c625345"; sha256 = "0b8lawi7kcws4axfsdf023gyxca15irl648ciyi1kw3wghz3pfi2"; };
} {
  name = "Pkg";
  uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Pluto";
  uuid = "c3e4b0f8-55cb-11ea-2926-15256bba5781";
  path = "P/Pluto";
  replaceUrlInManifest = null;
  treehash = "63f2a51822bc5f402d6f1175f1ed751102f9c39a";
  artifacts = {};
  src = fetchgit { url = "https://github.com/fonsp/Pluto.jl.git"; rev = "63f2a51822bc5f402d6f1175f1ed751102f9c39a"; sha256 = "0qyav677hfzapri3hl768ck0k1chmz47kzidgbhcy65grqnavbf1"; };
} {
  name = "PositiveFactorizations";
  uuid = "85a6dd25-e78a-55b7-8502-1745935b8125";
  path = "P/PositiveFactorizations";
  replaceUrlInManifest = null;
  treehash = "17275485f373e6673f7e7f97051f703ed5b15b20";
  artifacts = {};
  src = fetchgit { url = "https://github.com/timholy/PositiveFactorizations.jl.git"; rev = "17275485f373e6673f7e7f97051f703ed5b15b20"; sha256 = "1wxy6ak7f3hvibcgc8q88cgkf9zvi649mmjy1zlkx1qk80hgvz23"; };
} {
  name = "Printf";
  uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "QuadGK";
  uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc";
  path = "Q/QuadGK";
  replaceUrlInManifest = null;
  treehash = "12fbe86da16df6679be7521dfb39fbc861e1dc7b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/QuadGK.jl.git"; rev = "12fbe86da16df6679be7521dfb39fbc861e1dc7b"; sha256 = "1hy0629yai6xflgxaflk9764lzr1lzhlghimxk1aqi212q9c6n33"; };
} {
  name = "REPL";
  uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Random";
  uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Reexport";
  uuid = "189a3867-3050-52da-a836-e630ba90ab69";
  path = "R/Reexport";
  replaceUrlInManifest = null;
  treehash = "57d8440b0c7d98fc4f889e478e80f268d534c9d5";
  artifacts = {};
  src = fetchgit { url = "https://github.com/simonster/Reexport.jl.git"; rev = "57d8440b0c7d98fc4f889e478e80f268d534c9d5"; sha256 = "1yhhja1zz6dy5f4fd19bdwd6jwgj7q4w3avzgyg1hjhmdl8jrh0s"; };
} {
  name = "Requires";
  uuid = "ae029012-a4dd-5104-9daa-d747884805df";
  path = "R/Requires";
  replaceUrlInManifest = null;
  treehash = "cfbac6c1ed70c002ec6361e7fd334f02820d6419";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Requires.jl.git"; rev = "cfbac6c1ed70c002ec6361e7fd334f02820d6419"; sha256 = "14r49cz3dnbnrbrjnjn513z0lb6dpawkx7vmcwgs1cmc0rdxcz4a"; };
} {
  name = "Rmath";
  uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa";
  path = "R/Rmath";
  replaceUrlInManifest = null;
  treehash = "86c5647b565873641538d8f812c04e4c9dbeb370";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/Rmath.jl.git"; rev = "86c5647b565873641538d8f812c04e4c9dbeb370"; sha256 = "1745xajy5c8hdcy1hgi2rr9lrapr55hp0jm2dcb1ksyskvm5drsr"; };
} {
  name = "Rmath_jll";
  uuid = "f50d1b31-88e8-58de-be2c-1cc44531875f";
  path = "R/Rmath_jll";
  replaceUrlInManifest = null;
  treehash = "d76185aa1f421306dec73c057aa384bad74188f0";
  artifacts = {
    "fa7a95c807b2fbc4e13451994fe92463203ce891" = [{
      name = "Rmath";
      url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+1/Rmath.v0.2.2.x86_64-linux-gnu.tar.gz";
      sha256 = "59490caae4d04fd46cebd63d94bf6f7bbb147bb9471e5cbe616e05b6a2a1eca5";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl.git"; rev = "d76185aa1f421306dec73c057aa384bad74188f0"; sha256 = "13wvx4n0ai7bsda3rvlw8xbqwdbdwhjijbgjgl0k2yzq5l8x5dmh"; };
} {
  name = "SHA";
  uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce";
  path = "S/SHA";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Serialization";
  uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SharedArrays";
  uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Sockets";
  uuid = "6462fe0b-24de-5631-8697-dd941f90decc";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SortingAlgorithms";
  uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c";
  path = "S/SortingAlgorithms";
  replaceUrlInManifest = null;
  treehash = "03f5898c9959f8115e30bc7226ada7d0df554ddd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/SortingAlgorithms.jl.git"; rev = "03f5898c9959f8115e30bc7226ada7d0df554ddd"; sha256 = "1nz96sccgl6h6aknck59gmy1yrzx356kk9z68svj2g6yialprv1j"; };
} {
  name = "SparseArrays";
  uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SpecialFunctions";
  uuid = "276daf66-3868-5448-9aa4-cd146d93841b";
  path = "S/SpecialFunctions";
  replaceUrlInManifest = null;
  treehash = "5919936c0e92cff40e57d0ddf0ceb667d42e5902";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/SpecialFunctions.jl.git"; rev = "5919936c0e92cff40e57d0ddf0ceb667d42e5902"; sha256 = "1rfhrrkzi3ils7fklbn35ki1yp5x88fi71qknfwqyw4pk8cf8p80"; };
} {
  name = "Static";
  uuid = "aedffcd0-7271-4cad-89d0-dc628f76c6d3";
  path = "S/Static";
  replaceUrlInManifest = null;
  treehash = "98ace568bf638e89eac33c99337f3c8c6e2227b8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/SciML/Static.jl.git"; rev = "98ace568bf638e89eac33c99337f3c8c6e2227b8"; sha256 = "1pswwxdyng70sryxgv395yvdr0n96iw41sd97ly6cmjlf1alcw87"; };
} {
  name = "StaticArrays";
  uuid = "90137ffa-7385-5640-81b9-e52037218182";
  path = "S/StaticArrays";
  replaceUrlInManifest = null;
  treehash = "9da72ed50e94dbff92036da395275ed114e04d49";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/StaticArrays.jl.git"; rev = "9da72ed50e94dbff92036da395275ed114e04d49"; sha256 = "01z8bcqwpfkp8p1h1r36pr5cc3798y76zkas7g3206pcsdhvlkz1"; };
} {
  name = "Statistics";
  uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "StatsBase";
  uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91";
  path = "S/StatsBase";
  replaceUrlInManifest = null;
  treehash = "400aa43f7de43aeccc5b2e39a76a79d262202b76";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/StatsBase.jl.git"; rev = "400aa43f7de43aeccc5b2e39a76a79d262202b76"; sha256 = "1vc1dqi3zbza7dj5znqqwkv0k1zdrkqikza6fvxh3rps20g7wfrp"; };
} {
  name = "StatsFuns";
  uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c";
  path = "S/StatsFuns";
  replaceUrlInManifest = null;
  treehash = "3b9f665c70712af3264b61c27a7e1d62055dafd1";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/StatsFuns.jl.git"; rev = "3b9f665c70712af3264b61c27a7e1d62055dafd1"; sha256 = "0fhkx4clxlfixlb9hw7bsljfkv468k2y9s3f2cpaz7f5qbvgkmmq"; };
} {
  name = "SuiteSparse";
  uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9";
  path = "S/SuiteSparse";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "TableTraits";
  uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c";
  path = "T/TableTraits";
  replaceUrlInManifest = null;
  treehash = "b1ad568ba658d8cbb3b892ed5380a6f3e781a81e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/queryverse/TableTraits.jl.git"; rev = "b1ad568ba658d8cbb3b892ed5380a6f3e781a81e"; sha256 = "0lzb9xqnhgjbvkscc4p9vw3pzajm3a5a6ayv6byqc53ws8fxqk2v"; };
} {
  name = "Tables";
  uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c";
  path = "T/Tables";
  replaceUrlInManifest = null;
  treehash = "a716dde43d57fa537a19058d044b495301ba6565";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Tables.jl.git"; rev = "a716dde43d57fa537a19058d044b495301ba6565"; sha256 = "1265ak3gxxf1rx2rzj40jc9s6972x2v8ncm7qign1irr54knj8v6"; };
} {
  name = "Test";
  uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "URIs";
  uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4";
  path = "U/URIs";
  replaceUrlInManifest = null;
  treehash = "7855809b88d7b16e9b029afd17880930626f54a2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/URIs.jl.git"; rev = "7855809b88d7b16e9b029afd17880930626f54a2"; sha256 = "0fqyagsqks5za7m0czafr34m2xh5501f689k9cn5x3npajdnh2r3"; };
} {
  name = "UUIDs";
  uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "UnPack";
  uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed";
  path = "U/UnPack";
  replaceUrlInManifest = null;
  treehash = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/mauro3/UnPack.jl.git"; rev = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b"; sha256 = "066v1px72zidnvhl0rczhh07rcfwvli0jx5nprrgyi1dvj3mps2a"; };
} {
  name = "Unicode";
  uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
}];
}
