# This file is autogenerated, do not edit by hand!
{fetchgit}: {
  registryUrl = "https://github.com/JuliaRegistries/General.git";
  registryRev = "0560a070b9c10a87f7a6c166375d479072ada51a";
  registrySha256 = "10z1ymkdn2zm1ll40d885yr4js3pjfwn8vcz2p9hmyqxg1kz8cwh";
  rootPackages = ["IJulia"];
  closure = [{
  name = "Artifacts";
  uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33";
  path = "A/Artifacts";
  replaceUrlInManifest = null;
  treehash = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Artifacts.jl.git"; rev = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744"; sha256 = "0i0s26ypiwg6zyb3aqn9kiyiblkkab1mfac9plmq2jv4hggm4jfc"; };
} {
  name = "Base64";
  uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Conda";
  uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d";
  path = "C/Conda";
  replaceUrlInManifest = null;
  treehash = "c0647249d785f1d5139c0cc96db8f6b32f7ec416";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPy/Conda.jl.git"; rev = "c0647249d785f1d5139c0cc96db8f6b32f7ec416"; sha256 = "1v0plrhx9765kzynjdbgrxg5yv0nl40mklyl0z0p06ifvn927q77"; };
} {
  name = "Dates";
  uuid = "ade2ca70-3891-5945-98fb-dc099432e06a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Distributed";
  uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "FileWatching";
  uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "IJulia";
  uuid = "7073ff75-c697-5162-941a-fcdaad2a7d2a";
  path = "I/IJulia";
  replaceUrlInManifest = null;
  treehash = "d8b9c31196e1dd92181cd0f5760ca2d2ffb4ac0f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/IJulia.jl.git"; rev = "d8b9c31196e1dd92181cd0f5760ca2d2ffb4ac0f"; sha256 = "03vl36ryqs51rzlc14z04fpzh0z95a342gn3j3lzj5cmcrh45dhq"; };
} {
  name = "InteractiveUtils";
  uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "JLLWrappers";
  uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210";
  path = "J/JLLWrappers";
  replaceUrlInManifest = null;
  treehash = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"; rev = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0"; sha256 = "1sj3mi2dcc13apqfpy401wic5n0pgbck1p98b2g3zw0mln9s83m4"; };
} {
  name = "JSON";
  uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6";
  path = "J/JSON";
  replaceUrlInManifest = null;
  treehash = "81690084b6198a2e1da36fcfda16eeca9f9f24e4";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/JSON.jl.git"; rev = "81690084b6198a2e1da36fcfda16eeca9f9f24e4"; sha256 = "1f9k613kbknmp4fgjxvjaw4d5sfbx8a5hmcszmp1w9rqfqngjx9m"; };
} {
  name = "LibGit2";
  uuid = "76f85450-5226-5b5a-8eaa-529ad045b433";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libdl";
  uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Logging";
  uuid = "56ddb016-857b-54e1-b83d-db4d58db5568";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Markdown";
  uuid = "d6f4376e-aef5-505a-96c1-9c027394607a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MbedTLS";
  uuid = "739be429-bea8-5141-9913-cc70e7f3736d";
  path = "M/MbedTLS";
  replaceUrlInManifest = null;
  treehash = "1c38e51c3d08ef2278062ebceade0e46cefc96fe";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/MbedTLS.jl.git"; rev = "1c38e51c3d08ef2278062ebceade0e46cefc96fe"; sha256 = "0zjzf2r57l24n3k0gcqkvx3izwn5827iv9ak0lqix0aa5967wvfb"; };
} {
  name = "MbedTLS_jll";
  uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1";
  path = "M/MbedTLS_jll";
  replaceUrlInManifest = null;
  treehash = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6";
  artifacts = {
    "519367e9365948074c1fcc9f4365597f147a5ab7" = [{
      name = "MbedTLS";
      url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.8+0/MbedTLS.v2.16.8.x86_64-linux-gnu.tar.gz";
      sha256 = "5968d98ac1d4fdbf44ed87b0687f916f69ab077961b3cc9ea6068e2d739bd953";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl.git"; rev = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6"; sha256 = "0x43cp26p4w799i1cy4j72l5b1dyqcsab98qjw6yydxk2wha5vw4"; };
} {
  name = "Mmap";
  uuid = "a63ad114-7e13-5084-954f-fe012c677804";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Parsers";
  uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0";
  path = "P/Parsers";
  replaceUrlInManifest = null;
  treehash = "223a825cccef2228f3fdbf2ecc7ca93363059073";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Parsers.jl.git"; rev = "223a825cccef2228f3fdbf2ecc7ca93363059073"; sha256 = "0kwa1i3cbqhm4xpx0dwxy2dqyn7n63v0xg398hbw6wzz8ijj3b43"; };
} {
  name = "Pkg";
  uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Printf";
  uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "REPL";
  uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Random";
  uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SHA";
  uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce";
  path = "S/SHA";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Serialization";
  uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Sockets";
  uuid = "6462fe0b-24de-5631-8697-dd941f90decc";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SoftGlobalScope";
  uuid = "b85f4697-e234-5449-a836-ec8e2f98b302";
  path = "S/SoftGlobalScope";
  replaceUrlInManifest = null;
  treehash = "986ec2b6162ccb95de5892ed17832f95badf770c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/stevengj/SoftGlobalScope.jl.git"; rev = "986ec2b6162ccb95de5892ed17832f95badf770c"; sha256 = "1n3l0al1vw5jpb4k9a29a71666cdb617nmiqg34wcmyfzrxpvv39"; };
} {
  name = "Test";
  uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "UUIDs";
  uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Unicode";
  uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "VersionParsing";
  uuid = "81def892-9a0e-5fdd-b105-ffc91e053289";
  path = "V/VersionParsing";
  replaceUrlInManifest = null;
  treehash = "80229be1f670524750d905f8fc8148e5a8c4537f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaInterop/VersionParsing.jl.git"; rev = "80229be1f670524750d905f8fc8148e5a8c4537f"; sha256 = "060s72dsnpavgilf7f7315lw2sn4npk8lkndmj6bg7i23hppiwva"; };
} {
  name = "ZMQ";
  uuid = "c2297ded-f4af-51ae-bb23-16f91089e4e1";
  path = "Z/ZMQ";
  replaceUrlInManifest = null;
  treehash = "fc68e8a3719166950a0f3e390a14c7302c48f8de";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaInterop/ZMQ.jl.git"; rev = "fc68e8a3719166950a0f3e390a14c7302c48f8de"; sha256 = "1pn1gi11h7m7m5nnal0jqm2gcf1p6rzqqzd7wq2qb5vb5vi8p1zv"; };
} {
  name = "ZeroMQ_jll";
  uuid = "8f1865be-045e-5c20-9c9f-bfbfb0764568";
  path = "Z/ZeroMQ_jll";
  replaceUrlInManifest = null;
  treehash = "74a74a3896b63980734cc876da8a103454559fe8";
  artifacts = {
    "ea12a7226e04b693bc41a789040b5645d7faeaac" = [{
      name = "ZeroMQ";
      url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.2+6/ZeroMQ.v4.3.2.x86_64-linux-gnu-cxx11.tar.gz";
      sha256 = "1c1081d41b1ff929c89ee2be38d5e5da39303426046b9c59ffa61d1765912988";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl.git"; rev = "74a74a3896b63980734cc876da8a103454559fe8"; sha256 = "0hy9mpflw0cpfwqpzzypls9wainl27hk19vwbp2199i37wnwdhan"; };
} {
  name = "libsodium_jll";
  uuid = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8";
  path = "L/libsodium_jll";
  replaceUrlInManifest = null;
  treehash = "7127f5f40332ccfa43ee07dcd0c4d81a27d9bb23";
  artifacts = {
    "53913caaf6afb8d02133a1fdc6eec5112c9f7be1" = [{
      name = "libsodium";
      url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.x86_64-linux-gnu.tar.gz";
      sha256 = "997e80e7180be64f9c9e057ead0a970511fcc0ee7b88dc63694f97d0a778fc8b";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl.git"; rev = "7127f5f40332ccfa43ee07dcd0c4d81a27d9bb23"; sha256 = "166al10wzlvkq149ryx9n348fcrkb3wjfmm1pmxvcly2ffk9ih15"; };
}];
}
