[devshell]
startup.project_path.text = '''
export PATH=$PRJ_ROOT/bin:$PATH
'''

[[commands]]
name = "pluto"
category = "Julia Package"
command = '''
        julia -E "import Pkg; Pkg.activate(\".\"); Pkg.instantiate();using Pluto; Pluto.run(host=\"$1\", port=$2)"
        '''
help = "launch pluto server: pluto <ip> <port>"

[[commands]]
name = "addPackage"
category = "Julia Package"
command = '''
        julia -e "using Pkg; Pkg.activate(\"$1\"); Pkg.add([$2])"
        '''
help = "Exp: addPackage . '\"StatsFuns, Images\"' -> <activatePath> <Package Name List>"


[[commands]]
name = "upgrade"
category = "Julia Package"
command = '''
        julia -e "using Pkg; Pkg.upgrade_manifest(); Pkg.update()"
        '''
help = "Upgrading your manifest"


[[env]]
name = "JULIA_DEPOT_PATH"
value = "./.julia_depot"

# [[env]]
# name = "PATH"
# prefix = "bin"
