name: "CI"
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2

    - uses: nixbuild/nix-quick-install-action@v22
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Nix Flake Show
      run: nix -Lv flake show --impure
    - name: Nix Develop Check
      run: nix -Lv develop --impure -c echo OK
